### ISSUE TITLE
[BUG] When adding an environment to the watch files there is a bug in viewing the environment

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#265]
Complains during the authentication section.

![image](https://user-images.githubusercontent.com/1740337/158686612-1e222a46-1787-4963-9bdb-e2f83dbe41e2.png)

**Comment by costrouc** [comment]
I haven't seen this issue occur again. Going to close unless it shows up again.

**Comment by ericdwang** [comment]
I tested the latest version of conda-store (0.3.15) and it started throwing 500s when viewing any environment, not just ones created from watching files:

![image](https://user-images.githubusercontent.com/2069450/163285668-e13df70e-1583-4907-a947-2d413b79bbe8.png)

This still happens when downgrading back to 0.3.11 as well.

**Comment by costrouc** [comment]
Thanks @ericdwang for these error logs. I'm going to work on updating qhub-hpc to use the latest conda-store.

**Comment by kcpevey** [comment]
@costrouc can you provide an update on this issue? Has this been resolved?

**Comment by pierrotsmnrd** [comment]
This issue doesn't have a reproduction scenario, and is quite old.
I marked it as stale, I suggest we close it - unless indicated otherwise by @costrouc

**Comment by costrouc** [comment]
Yeah this is fine to close. I haven't seen this issue
