### ISSUE TITLE
The default namespace should also be shown as a kernel without a namespace.

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#289]
For example suppose the default namespace is `default`.

`default/datascience` should be the same as `datascience` this is consistent. This may be controvertial and is up for discussion main motivation is notebooks that have the environment set to `datascience` have to be manually fixed to point to `default/datascience`

**Comment by kcpevey** [comment]
@costrouc I don't understand this issue. Is it still valid and if so, can you provide more information?

**Comment by trallard** [comment]
I do  not think this would be useful from a user experience POV:

1. Environments _only_ exist within a namespace - removing the namespace intentionally (even if at the representation level only) from the `default` environment might cause mental model issues/confusion with the users.
2. On a regular JupyterLab workflow, users are expected to select the correct kernel for a given notebook (there are exceptions, though). Users are already familiar with this workflow, so this is not adding more friction.
3. Tangential to 1. but if a user has multiple environments with the same name across various namespaces, hiding/removing the namespace name within the `default` context can lead to confusion from the user POV.

Closing since there has not been a follow up and there does not seem to be a need for this
