### ISSUE TITLE
CondaStore.conda_allowed_channels should by default allow all channels

### ISSUE THREAD

**Issue by dharhas** [conda-incubator/conda-store#357]
Why is 'allowed channels' hardcoded in:

https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/app.py

Can these be overridden in config. Why not allow any channel by default?

This relates to pr #354 as well since that I think isn't the ideal way to fix this issue.

@costrouc @iameskild

**Comment by costrouc** [comment]
> Do we NEED to hardcode the allowed channels?

I think for a default value we should allow all channels. So we should likely make the default value for `conda_allowed_channels = []` to allow all channels. This seems to be more in line with the expected behavior from users.

> How are users expected now to deal with channels when creating their environments?

I'd say this is the responsibility of the UI? There is a channel api endpoint that could we used to help the user. However the channels endpoint will only list channels that are currently used by environments and in the `CondaStore.conda_indexed_channels` attribute.

**Comment by trallard** [comment]
> I'd say this is the responsibility of the UI? 

This aligns with other issue discussions so I will do my best to clarify this point (I feel the term UI is being used as an abstract catch-all for all things user-interaction related). The UI is an interface or a layer for the user to interact with the tool or system. 
What is essential is the workflow (what is happening and how?) and how this translates into user interaction (what is the user trying to achieve? Are we matching this or facilitating this with the underlying workflow). Then the UI provides visual (or other) components (buttons, dropdowns, etc.) to improve the user experience and simplify the human-machine interaction. Workflows guide UI implementations. 

For example, for the question, "How are users expected now to deal with channels when creating their environments?" my answer would be:
* The user provides the channels within their (environment.)yaml specification

Because
1. Users are already familiar with this workflow -> specify dependencies and channels in their environment.yaml files
2. We are not restricting the user with opinionated defaults/restrictions instead we are giving them the flexibility they need to do what they need to do

**Comment by kcpevey** [comment]
>Do we NEED to hardcode the allowed channels?

This is an option on the backend because there is a usecase where a company may want to restrict what channels are available for the users (i.e. you cannot use defaults due to terms of use constraints). So I see value in the option, but the default should be to accept all channels.

That said, I dont think we have a good mechanism to convey this restriction to end users via the UI (I've never hit this so I really don't know how it would respond or fail).

**Comment by trallard** [comment]
That is a valid use case *but* it has to be a user-made choice/setting, not a blanket default as it currently is.

We should then think about how to enable this separately.

**Comment by kcpevey** [comment]
@nkaretnikov will be working on this issue
