### ISSUE TITLE
CondaStoreServer.log_level doesn't do anything

### ISSUE THREAD

**Issue by asmeurer** [conda-incubator/conda-store#516]
`CondaStoreServer.log_level` nominally controls the logger level (see https://conda.store/en/latest/administration.html#conda-store-server-server-app-condastoreserver), but [it's never actually used anywhere](https://github.com/search?q=repo%3Aconda-incubator%2Fconda-store%20log_level&type=code).

Furthermore, the log level is difficult to set at the command line because `--CondaStoreServer.log_level=DEBUG` doesn't work. You'd have to use `--CondaStoreServer.log_level=10` (where `logging.DEBUG == 10`).

**Comment by trallard** [comment]
If this is not used, and it is otherwise not adding anything in terms of user experience (CLI use) would it not be best to remove this altogether?

**Comment by pavithraes** [comment]
@costrouc @pierrotsmnrd - What do you think about this?

**Comment by trallard** [comment]
@costrouc last ping here. Otherwise will just move ahead with removing this altogether.

**Comment by costrouc** [comment]
I think this is a worthwhile issue to look into since this is the primary way that we debug things within a kubernetes deployment on nebari. I'd also say logging/printing in conda-store-server/worker(s) is inconsistent and needs clean up. Traitlets does provide a log attribute to LoggingConfigurable classes but it is not always accessible where you need.

**Comment by trallard** [comment]
@nkaretnikov can you please take on this issue?

**Comment by peytondmurray** [comment]
Closed by #940.
