### ISSUE TITLE
[ENH] - status for cancelled build

### ISSUE THREAD

**Issue by pierrotsmnrd** [conda-incubator/conda-store#547]
### Feature description

Once PR #531 is merged, we'll have the possibility to cancel builds.
In the current state of this feature, a cancelled build has a "Failed" status.

Implementing a clear "Cancelled" status would be clearer for the users. 
Implementing this would imply adding an Alembic migration

### Value and/or benefit

- Clearer build status for the users

**Comment by kcpevey** [comment]
@pierrotsmnrd it looks like #531 implements the backend for cancelling builds and this issue is focussed on the front end. Is that correct?

![image](https://github.com/conda-incubator/conda-store/assets/15659110/a7b90150-eb5d-404e-8659-c374755af0c5)

Thinking through the UX:

`How do I know a build is cancelled?`:  
The "CANCELLED" status should just be similar to the Available/Failed/Active field in the above image. Is anything else missing for that to work?

`How do I cancel a build?`:  
We need some design work here to decide how and where to present this to users.
* Will it have a popup confirmation modal?
* After clicking to cancel a build, will the UI element (e.g. button) change from "Cancel" to "Cancelling" or something to indicate that its working?

**Comment by costrouc** [comment]
> @pierrotsmnrd it looks like https://github.com/conda-incubator/conda-store/pull/531 implements the backend for cancelling builds and this issue is focussed on the front end. Is that correct?

@kcpevey this issue is focusing on the issue that currently conda-store-server's schema for BuildStatus only knows of queued, building, failed, completed. We're adding a new status `canceled` which signifies that the build did not fail but was explicitly canceled.

There are several places in conda-store-server where build status implies which actions are allowable and should be taken and this issue/PR will need to address that.

**Comment by nkaretnikov** [comment]
See https://github.com/conda-incubator/conda-store/pull/531#discussion_r1298255606

**Comment by pavithraes** [comment]
#531 is merged, this issue is now unblocked :)
