### ISSUE TITLE
Conda-store one shot ability to freeze a reproducible environment

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#63]
The idea of using conda-store as a github action to create a docker image, conda lock, conda pack of a given environment.

cc: @jaimergp

**Comment by jaimergp** [comment]
See these for inspiration / overlap:

* https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2
* https://github.com/jupyterhub/repo2docker-action

**Comment by peytondmurray** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
