### ISSUE TITLE
Unify user-facing error messages

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#663]
### Context

Ideas:
- Support localization
- Make sure all user-facing messages are defined in one place and have custom exceptions defined for them
- In some cases, we might not want to tell the user too much, since it might expose sensitive information about the system (what files are being accessed, etc.). But we might want to still codify the message, such as: "Error 12345: Something went wrong".
- For the same reason, we need to make sure these messages are hardcoded and not just bubble up from some library throwing an exception.
- Move the current exceptions from utils into a file called exceptions.

See:
- https://github.com/conda-incubator/conda-store/pull/653#pullrequestreview-1729775710
- https://github.com/conda-incubator/conda-store/pull/653#discussion_r1390449347

### Value and/or benefit

.

**Comment by nkaretnikov** [comment]
cc @jaimergp

**Comment by peytondmurray** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
