### ISSUE TITLE
Handle multiple OS/architectures builders for workers

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-store#71]
There are some places where os/arch is assumed to be `linux-64`. For example, [lockfiles](https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/api.py#L82).

AFAIK there's no way to tell `conda-store` which os/arch should be targeted either. It would just assume it is the one running in the underlying Docker image for `conda-store-server`.

**Comment by costrouc** [comment]
I think that it is important to support arm64 and x86. However I don't see much value at the moment of supporting osx since the main motivation for this work is allowing dockerized environments and linux hpc environments access to conda environments. Going to put in the icebox.

**Comment by jaimergp** [comment]
Agree that `osx` is not priority at all. But `aarch64` and `ppc64le` might be needed at some point. With #77 once can get those environments as long as `conda-store-server` is running on those archs, but #67 forces the Dockerfiles to be x64.

**Comment by trallard** [comment]
Related to #507

**Comment by asmeurer** [comment]
What exactly is the issue to be done here? With #539 conda-store in standalone mode works on macOS, and generates lockfiles with osx-64. I don't have an ARM mac to test, but it would presumably work there too. The Docker generation is disabled on Mac, because conda-docker does not work on Mac. Is the point here to be able to generate environments for architectures different from the one conda-store is running in?

**Comment by costrouc** [comment]
@asmeurer changed the name of the issue since I think this issue is independant from the standalone work. But I do think that working on the standalone work makes this work much easier.

I'm not sure how to test or do this but I would like to have a separate celery worker/queue per OS/architecture. This would allow us to truely build environments for all OS's. I think this is a hard issue.

**Comment by asmeurer** [comment]
I see. Presumably, for most actions, you could just build an environment for a different platform than the one the worker is running on by setting the appropriate environment variables/flags to conda to make it use a different arch. Although there are definitely some actions that just won't work with, e.g., what comes to mind would be

- Building a docker container (because of the conda-docker issues noted elsewhere)
- pip installing anything that involves compilation. Presumably building a cross-platform env with a pure Python .tar.gz or a wheel is fine, although I don't actually know how to do it. 

And possibly some other things as well. Has this sort of thing already been considered?

For actually having the workers run on multiple OSes, the obvious blocker is #507. macOS support should be working now (sans Docker container building). Windows support is next but will probably be harder. 

Outside of that, I guess there's the basic issue of keeping track of which workers are available and which should be used for a given task.

Another question is the actual underlying store. You'd presumably want separate stores for different architectures, e.g., a Windows environment should probably be stored in an actual Windows filesystem. Is that sort of thing already supported?

**Comment by pavithraes** [comment]
Next steps: @asmeurer and @trallard will sync with @jaimergp on the details.

**Comment by costrouc** [comment]
Windows, Linux, OSX believe are supported. The only non-tested platform is arm MacOS.

**Comment by asmeurer** [comment]
ARM Mac is used on the CI. I did only test locally on Intel Mac, although I don't know if others tested locally on ARM Mac.

**Comment by jaimergp** [comment]
Right now our multiplatform support assumes that the worker is running on the native platform, right? In other words, to create Windows environments, conda-store needs to be running on Windows. 

Is there support to do cross-solving? e.g. I have conda-store on Linux x64, but want to provide environments for Windows machines. `conda 23.10` supports this now via `--platform` (and `micromamba` has done it for a while too, same as conda-lock). We might have some issues with some artifacts, but I want to know how deeply engrained is the assumption that `target_arch == machine_arch`.
