### ISSUE TITLE
[BUG] - conda-store forces ipykernel to be added in non-python environments

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#769]
### Describe the bug

Original issue reported [here](https://github.com/nebari-dev/nebari/issues/2272). 

>I created a global environment called "R" in conda store. I requested r-irkernel and r-essentials dependencies. It seems that ipykernel is added by default. I believe due to r-irkernel and ipykernel being installed we get 2 new kernels showing up from the jupyterlab interface (screenshot below), one which expects python code and one which expects R code

We confirmed that only ONE environment is created, but it has TWO kernels. 

### Expected behavior

>Only 1 new kernel. Don't add ipykernel if r-irkernel is installed.

This should also be true for other non-python kernel's we support (julia?)

### How to Reproduce the problem?

Create a new env and add `r-irkernel` and `r-essentials` dependencies.

### Output

Go to jupyterlab launcher screen and view the two different kernels

### Anything else?

from brief investigation by @dcmcand :

>Having looked into this, it would definitely need fixed on the conda-store side. There are a couple of ways that I could think to approach this.
>
>Add a new config option for jupyterlab support. That would automatically add ipykernel unless irkernel is requested. This has the advantage that we could get specific with our logic without complicating the conda_include_packages config option. It would be pretty straightforward to implement. The disadvantage is we are hard coding usecase specific logic. That is generally not good, but may be ok here since jupyterlab is used so widely.
>
>Add an option to the api route that creates environment to ignore auto included packages. This option could then be exposed in the ui. The default would be to include the automatic packages, but a user could choose to override that. This has the advantage of greater flexibility, we aren't writing a single purpose solutions, but users could also get themselves into trouble and could create environments that did not have packages that were set as auto include in the config. I don't think that this would be particularly difficult to implement, but would require ui work as well as server side work.

**Comment by krassowski** [comment]
> 1. Add a new config option for jupyterlab support. That would automatically add `ipykernel` unless `irkernel` is requested. This has the advantage that we could get specific with our logic without complicating the conda_include_packages config option. It would be pretty straightforward to implement. The disadvantage is we are hard coding usecase specific logic. That is generally not good, but may be ok here since jupyterlab is used so widely.

There are >200 kernels for Jupyter (some are listed [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) but the list is not exhaustive). I would not recommend this approach.

> 2. Add an option to the api route that creates environment to ignore auto included packages. This option could then be exposed in the ui.

IMO this is the best solution because there is no way to know upfront whether a package will produce a kernelspec prior to actually installing it.

**Comment by dcmcand** [comment]
> IMO this is the best solution because there is no way to know upfront whether a package will produce a kernelspec prior to actually installing it.

thanks @krassowski , that was my preferred solution too, but I appreciate the additional context about Jupyter.

**Comment by trallard** [comment]
I am assuming this was reported from a conda-store instance in nebari.

Looking into the configuration, ipykernel will always be installed due to [`c.CondaStore.conda_included_packages = ["ipykernel"]`](https://github.com/nebari-dev/nebari/blob/6d9abb03ef5cd0c987abe11090f4748676e3b0ee/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py#L38)

Per the docs, any package listed in such a configuration _will always be added_ even if not included in the specification, ref: https://conda.store/conda-store/references/configuration-options

So rather than a bug in conda-store this should be reverted in the configuration for nebari.

Will close this issue and if fixing that config does not solve this, we can reopen it.

**Comment by krassowski** [comment]
There seems to be a thing that can be done on conda-store side, which was mentioned in the usability study:

https://github.com/conda-incubator/conda-store/blob/3d404b6a173fdd30c6556b8b68dc8fbd8011c586/docusaurus-docs/community/design/usability-study.md?plain=1#L91

Does this warrant creating a new issue in conda-store-ui maybe?

**Comment by krassowski** [comment]
Alternatively to the idea of notification, could user have a checkbox to un-click which says "[x] include default packages (ipykernel, X, Y)"

**Comment by trallard** [comment]
Yes I was planning to open another issue on UI to this effect but I need to log off. Could you take care of this @krassowski ?
Probably the checkbox would be the easiest one.
