### ISSUE TITLE
[BUG] -  Memory leaks during environment creation tasks 

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#848]
### Describe the bug

See https://github.com/nebari-dev/nebari/issues/2418 and #840 for context. TLDR: `action_add_conda_prefix_packages` is leaking memory, causing problems on various nebari deployments.

edit by @trallard: It seems `action_add_conda_prefix_packages` is not the main or at least not the sole culprit of memory leaks so I adjusted the title

Memray flamegraph:

![image](https://private-user-images.githubusercontent.com/23342526/346819294-70cca917-3ced-41e0-9c3d-b90c320678a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDMwMzMsIm5iZiI6MTcyMDUwMjczMywicGF0aCI6Ii8yMzM0MjUyNi8zNDY4MTkyOTQtNzBjY2E5MTctM2NlZC00MWUwLTljM2QtYjkwYzMyMDY3OGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDI5OTRkMjg0NjMxMGM2N2Q3OTdkNjVkM2E3N2ExYTZkOTJiNjJiZWQyZmZmYmNhZmY2ZTM5NTFkZjI5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYbZBYcnieMNh6rR_xODsnjwc7uGhml9j2VP6enGUZk)

### Expected behavior

No memory leaks.

### How to Reproduce the problem?

See https://github.com/nebari-dev/nebari/issues/2418 for a description.

**Comment by Adam-D-Lewis** [comment]
The way I generated the flamegraph was to run `docker compose up --build -d` to start up the docker containers after I made a few changes including adding memray to the docker container.  I then ran `docker compose exec -it conda-store-worker bash` to get a shell in the container.  I waited until the worker seemed idle then I attached memray to the running process with `memray attach --native <pid> -o myfile.bin` to the process which I believe was celery worker.  I then logged into the UI at localhost:8080/conda-store/admin and created a bunch of environments with very littile in them (just the nothing package installed by pip used in some of the tests).  I then copied the myfile.bin out of the docker container with `docker cp <container_id>:/path/to/myfile.bin .`.  I then generated the flamegraph with `memray flamegraph --leaks myfile.bin`.

**Comment by trallard** [comment]
Per @Adam-D-Lewis's comment above about seeing memory increases even after bypassing the initially flagged action, we need to do a more in-depth profiling analysis.

**Comment by Adam-D-Lewis** [comment]
I tried restricting the docker container to 1 GiB of memory usage, and the memory growth per build was then less than 18Mb per build, but did increase, and eventually the celery worker was restarted due to memory usage.  I'm wondering if the excess 11Mb of memory growth in the docker container when I had no memory limit specified were just due to python being a memory managed language and that the memory usage from garbage collected objects is not always given back to the OS.

That being said, I think it should still be possible to write a test showing the memory usage grows to the point where a celery worker runs out of memory.

**Comment by peytondmurray** [comment]
That sounds fine; closing now. Anyway, even if there was a leak we are now restarting workers regularly so the symptom is in principle avoided even if any underlying leak (if any) isn't solved.

**Comment by kcpevey** [comment]
I'm running conda-store-ui locally with a fresh build. My creation of an env with `python` and `rich` is making the conda-store worker eat 10+GB of RAM. Even if the workers get restarted, this doesn't seem right?

**Comment by trallard** [comment]
Are you running this in Docker or standalone? 
@peytondmurray could not reproduce any mem leeks IIRC and neither could I last time I looked into this.

**Comment by peytondmurray** [comment]
> I'm running conda-store-ui locally with a fresh build. My creation of an env with python and rich is making the conda-store worker eat 10+GB of RAM. Even if the workers get restarted, this doesn't seem right?

If you're using `docker compose up --build`, it would also be good to know whether this happens after you've freshly started the services. From your description it feels like something the worker is doing is actually eating memory, rather than leaking it slowly over time.

**Comment by kcpevey** [comment]
I was using `docker compose up --build`. And yes, it does seem like something the worker is doing rather than a slow leak. 

I was trying to look at the logs but I dont know what all the output means. For example, it seems like a "bulk save" task is rather time consuming and unrelated to any env build I'm doing, but I don't know what that is or what it does.
