### ISSUE TITLE
[ENH] - Sunset the changelog

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#963]
### Feature description

I'd like to sunset `CHANGELOG.md`:

- To make it requires an extra step during the release process, which already requires a bunch of manual intervention
- The process for making it requires using [`github-activity`](https://github.com/choldgraf/github-activity) which doesn't see maintenance (although this is a fork, maybe we should use the upstream project?). It also doesn't allow you to use `gh auth`, so every time I make a release I need to mint a new PAT
- The biggest reason to get rid of it is this is already something that the github web interface has a button for when releasing:

![Image](https://github.com/user-attachments/assets/7cd28720-332c-49ed-a4a1-665790117b80)

@soapy1 @trallard @pavithraes thoughts?

### Value and/or benefit

Fewer release steps, and less chance for human error when publishing the changelog.

**Comment by soapy1** [comment]
+1 sounds good to me. I think the generated release notes are pretty sweet.

**Comment by trallard** [comment]
>  The process for making it requires using [github-activity](https://github.com/choldgraf/github-activity) which doesn't see maintenance (although this is a fork, maybe we should use the upstream project?). It also doesn't allow you to use gh auth, so every time I make a release I need to mint a new PAT

Not really. This is a suggestion, but nothing requires using such a tool (I intentionally added this as a footnote suggestion not to force folks to stick to a tool). The release captain can choose the best approach that suits them for this.

> +1 sounds good to me. I think the generated release notes are pretty sweet.

I partially disagree here; while they are complete, the generated release notes clump everything together, making it harder for users to identify user-facing enhancements or deprecations.
The reason for having a changelog doc is to aim and follow https://keepachangelog.com/en/1.1.0/  or something similar that separates the types of changes included in a given release.

So, if the team still wants to proceed and remove the changelog, I think an intentional effort should be made to make the auto-generated release notes easier for end-users to parse (of course, this will still need to be a release captain's responsibility during the release process, so it would continue to require some sort of manual work 🤷‍♀ ).

**Comment by soapy1** [comment]
I think @trallard makes some really great points about the value of keeping the CHANGELOG.md. The changes introduced in https://github.com/conda-incubator/conda-store/pull/1006 will automatically generate the release notes (the releaser should update them to be a bit more human friendly). This should decrease the work going into keeping the changelog up to date for each release. 

@peytondmurray I feel good about closing this issue if you do.
